@startuml
'https://plantuml.com/class-diagram

class Player extends Entity{
}

class PlayerControlSystem implements IEntityProcessingService{
+ void process(GameData gameData, World world);
- Collection<? extends BulletSPI> getBulletSPIs();
}

class PlayerPlugin implements IGamePluginService{
- Entity player;
- boolean death;
+ PlayerPlugin();
+ void start(GameData gameData, World world);
- Entity createPlayerShip(GameData gameData);
+ void stop(GameData gameData, World world);
}

@enduml