@startuml
'https://plantuml.com/component-diagram

[Asteroids]
[Asteroids] --> [Common]
[Asteroids] -[#purple]-( SplitAsteroids
[Asteroids] -[#green]-( IGamePluginService
[Asteroids] -[#red]-( IEntityProcessingService
[Asteroids] -[#blue]-( IPostEntityProcessingService

[Bullet]
[Bullet] -[#purple]-( BulletSPI
[Bullet] -[#green]-( IGamePluginService
[Bullet] -[#red]-( IEntityProcessingService

[Enemy]
[Enemy] -[#green]-( IGamePluginService
[Enemy] -[#red]-( IEntityProcessingService

[Player]
[Player] -[#green]-( IGamePluginService
[Player] -[#red]-( IEntityProcessingService


[CommonAsteroids] -[#purple]- SplitAsteroids


[CommonBullet] -[#purple]- BulletSPI

[Common] -[#green]- IGamePluginService
[Common] -[#blue]- IPostEntityProcessingService
[Common] -[#red]- IEntityProcessingService

[Collisions]
[Collisions] -[#red]-( IPostEntityProcessingService

[Core]

[Plugins]

@enduml