@startuml
'https://plantuml.com/component-diagram

[Core] -[#red]-( IGamePluginService
[Core] -[#blue]-( IEntityProcessingService
[Core] -[#green]-( IPostEntityProcessingService

[Asteroids] -[#red]- IGamePluginService
[Asteroids] -[#blue]- IEntityProcessingService
[Asteroids] -[#green]- IPostEntityProcessingService
[Asteroids] -[#purple]- SplitAsteroids

[Bullet] -[#red]- IGamePluginService
[Bullet] -[#blue]- IEntityProcessingService
[Bullet] -[#purple]- BulletSPI

[Enemy] -[#red]- IGamePluginService
[Enemy] -[#blue]- IEntityProcessingService

[Player] -[#red]- IGamePluginService
[Player] -[#blue]- IEntityProcessingService

[Collisions] -[#green]- IPostEntityProcessingService

@enduml

//Husk, at lave små UML Klassediagrammer for hvert modul.
//Derefter lav et pakkestruktur, hvor du skaber inheritance mellem dem.
