@startuml
'https://plantuml.com/sequence-diagram

actor User

User --> Core : Start Program
activate Core

Core --> Player : Use Arrow Controls
deactivate Core
activate Player

Player --> Bullet : Press Space, which shoots
deactivate Player
activate Bullet

Bullet --> Collision : Collision happens
activate Collision
Collision --> Bullet : setDeath on Bullet, if Player is shot/collides
deactivate Bullet

Other_Entities --> Collision : Enemy or Asteroids is shot/collides
activate Other_Entities
Collision --> Other_Entities : setDeath on Enemy or Asteroids
deactivate Other_Entities


@enduml